SPORT_PRODUCT = 'Sport product'
PRODUCT = 'Default'

SPORT_PRODUCTS_SHEET_NUMBER = 5

PRICE_MARGINE = 1.5


CELL_NUMBER = 43
BLANK = ''
SPORT_BARCODE = 0
SPORT_SKU = 1
SPORT_TYPE_OF_SPORT = 2 
SPORT_TYPE_OF_PRODUCT = 3
SPORT_TITLE = 5
SPORT_SHORT_DESCRIPTION = 8 
SPORT_BRAND = 15
SPORT_PRICE = 20
SPORT_CONDISION = 22 
SPORT_QUANTITY = 23
SPORT_CUSTOM_DESC = 24
SPORT_ADVERT_COMMENT = 25
SPORT_MAIN_PICTURE = 28
SPORT_PIC2 = 29
SPORT_PIC3 = 30
SPORT_SHIP_BY_RAKUTEN = 33 
SPORT_SHIPPING_FRANCE = 34
SPORT_SHIPPING_OVERSEAS = 35
SPORT_SHIPPING_EUROPE = 36 
SPORT_SHIPPING_WORLD = 37

BARCODE = "BARCODE"
SKU = "SKU"
PRICE = "PRICE"
CUSTOM_DESC = "CUSTOM_DESC"
MAIN_PICTURE = "MAIN_PICTURE"
PIC2 = "PIC2"
PIC2 = "PIC2"

TYPE_OF_SPORT = "TYPE_OF_SPORT"
TYPE_OF_PRODUCT = "TYPE_OF_PRODUCT"
TITLE = "TITLE"
SHORT_DESCRIPTION = "SHORT_DESCRIPTION"
BRAND = "BRAND"

TYPE_OF_SPORT_LIST= [
    "Alpinisme ",
    "Arts martiaux mixtes",
    "Athlétisme ",
    "Badminton ",
    "Base Ball",
    "Basket Ball ",
    "Bateau",
    "Beachvolley ",
    "Bobsleigh ",
    "Bodyboard ",
    "Bowling ",
    "Boxe",
    "Canoë - Kayak ",
    "Canyon - Spéléologie ",
    "Canyoning ",
    "Cerf-volant ",
    "Chasse ",
    "Cricket",
    "Cyclisme ",
    "Danse ",
    "Equitation ",
    "Escalade ",
    "Escrime ",
    "Fitness ",
    "Football ",
    "Football américain ",
    "Golf ",
    "Gymnastique ",
    "Handball ",
    "Hockey sur glace ",
    "Judo ",
    "Karaté ",
    "Karting ",
    "Kendo - Aïkido ",
    "Kite surf ",
    "Kung Fu ",
    "Luge de vitesse ",
    "Monoski ",
    "Moto ",
    "Mountainboard",
    "Musculation ",
    "Natation ",
    "Padel",
    "Parachutisme ",
    "Parapente ",
    "Patin à roulettes ",
    "Patinage artistique ",
    "Pêche ",
    "Pétanque ",
    "Planche à voile ",
    "Plongée ",
    "Polo ",
    "Rallye ",
    "Randonnée ",
    "Roller ",
    "Rugby ",
    "Running",
    "Saut à l'élastique ",
    "Skate ",
    "Ski",
    "Ski Alpin",
    "Ski de fond, nordique",
    "Ski de randonnée ",
    "Ski nautique ",
    "Snowboard ",
    "Squash ",
    "Stand up Paddle",
    "Surf ",
    "Taekwondo ",
    "Télémark",
    "Tennis ",
    "Tennis de table ",
    "Tir à l'arc ",
    "Trottinette ",
    "Voile ",
    "Volley-ball ",
    "Wakeboard ",
    "Water polo ",
    "Yoga"
]

TYPE_OF_PRODUCT_SPORT_LIST = [
    "Acides Aminés & BCAA's",
    "Après l'effort",
    "Avant l'effort",
    "Barres Protéinées",
    "Bruleurs de Graisse",
    "Capsules CLA",
    "Créatine",
    "Gainers",
    "Glutamines",
    "Huiles & Oméga 3",
    "Hydrates de Carbone",
    "Oxyde Nitrique",
    "RTD",
    "Shakers",
    "Stimulateurs Testostérone",
    "Substituts de repas",
    "Tout-en-un",
    "Vitamines & Minéraux",
    "Whey Protéiné",
    "Abreuvoir",
    "Abris",
    "Accastillage",
    "Accessoires bateau",
    "Accessoire montage ligne",
    "Accessoire moteur",
    "Accessoire pêche",
    "Accessoires de chasse",
    "Accessoires musculation",
    "Affûte-carres",
    "Aile ",
    "Allume-cigare",
    "Altimètres ",
    "Amortisseur ",
    "Ancre grappin",
    "Ancre plate",
    "Anémomètre ",
    "Anneaux d'attache",
    "Antivibrateur",
    "Antivol",
    "Appareil à charge guidée ",
    "Appareil de fitness ",
    "Appareil de navigation",
    "Appareil de signalisation ",
    "Appareil dos ",
    "Appareil Electrostimulation",
    "Appareils abdominaux",
    "Appât",
    "Appât et amorce",
    "Appeau",
    "Aquabike",
    "Arbalète",
    "Arc ",
    "Ardoise",
    "Armes à billes ",
    "Armes de jet",
    "Armes d'entraînement",
    "Armure ",
    "ARVA",
    "Assiette chinoise",
    "Assouplisseur",
    "Assureur",
    "Attache",
    "Attelage ",
    "Aviron ",
    "Badge ",
    "Bagagerie",
    "Bagagerie et rangement",
    "Balance électronique",
    "Balle ",
    "Balle de golf",
    "Balles de gym",
    "Ballon ",
    "Banc de Musculation ",
    "Bande de polo",
    "Bande de repos",
    "Bande de travail",
    "Bandeaux",
    "Bandes ",
    "Barque",
    "Barre",
    "Barre de musculation",
    "Barre de traction ",
    "Bateau",
    "Bâton ",
    "Batte ",
    "Batterie",
    "Baudriers ",
    "Baume pour cuir",
    "Bavette",
    "Béquille",
    "Bidon ",
    "Billard américain",
    "Billards Français ",
    "Bille ",
    "Bloc de départ ",
    "Blocage de  roue",
    "Blocage de selle",
    "Bloqueur mécanique ",
    "BMX (bi-cross) ",
    "Bobsleigh ",
    "Bodyboard ",
    "Bois",
    "Boitier de pédalier",
    "Bombe ",
    "Bonnet",
    "Boomerang",
    "Boots",
    "Bouchon ",
    "Boucle ",
    "Bouclier ",
    "Bouée ",
    "Bouée de sauvetage",
    "Bouée élévatrice ",
    "Bougie",
    "Boule ",
    "Boulier ",
    "Bourriche",
    "Boussole",
    "Bouteille ",
    "Bouteille de Plongée ",
    "Boyau ",
    "Bracelet ",
    "Bracelet connecté",
    "Brassard ",
    "Bretelle",
    "Brides ",
    "Bridon ",
    "Brique",
    "Broche à glace ",
    "Brosse",
    "Brosse tapis ",
    "Bruiteur",
    "But",
    "Câble et gaine",
    "Cadre ",
    "Cadre tatamis ",
    "Cagoule",
    "Calculateur d'estime",
    "Cale ",
    "Cale-pied ",
    "Canne ",
    "Canne à pêche ",
    "Canoë ",
    "Canon",
    "Capuchon",
    "Cardiofréquencemètre ",
    "Carquois",
    "Cartouchière",
    "Casque ",
    "Casque junior",
    "Casquette",
    "Cassette",
    "Catadioptre",
    "Caveçon",
    "Ceinture",
    "Ceinture Electrostimulation",
    "Cerceau ",
    "Cerf-volant ",
    "Chaîne ",
    "Chaise-lit",
    "Chambre à air ",
    "Chambrière",
    "Chaps ",
    "Chargeur ",
    "Chargeur de billes ",
    "Chariot ",
    "Chaufferette",
    "Chaussant ",
    "Chemise d'écurie ",
    "Chemise séchante",
    "Chevillère",
    "Chronomètre",
    "Cible",
    "Cintre ",
    "Cire ",
    "Ciseaux",
    "Clé ",
    "Cloche",
    "Club ",
    "Cochonnet ",
    "Coinceur",
    "Colle",
    "Collier",
    "Collier de chasse",
    "Collier de selle",
    "Combinaison ",
    "Combinaison de ski ",
    "Combinaison néoprène ",
    "Compas",
    "Compléments alimentaires",
    "Compresseur ",
    "Comprimé",
    "Compteur ",
    "Cones",
    "Coquille ",
    "Cordage ",
    "Corde à sauter ",
    "Corde d'attache ",
    "Corde de sécurité ",
    "Corde flottante",
    "Cordes ",
    "Cordes à sauter",
    "Corne ",
    "Corne d'appel",
    "Corsaire",
    "Coudière ",
    "Coupe-suspente ",
    "Coussinet ",
    "Couteau ",
    "Couteau à glace",
    "Couteau de Plongée ",
    "Couverts",
    "Couverture",
    "Couverture de survie ",
    "Couverture extérieure ",
    "Couvre siège",
    "Craies",
    "Crampons ",
    "Cravache ",
    "Crochet ",
    "Crosse",
    "Croupière",
    "Cuiller",
    "Cuirasse de protection ",
    "Cuissard ",
    "Cure pieds - Peigne",
    "Curvimètre",
    "Dague ",
    "Dégaine",
    "Dérailleur arrière ",
    "Dérailleur avant ",
    "Dérive",
    "Descendeur ",
    "Détecteur",
    "Détendeurs de Plongée ",
    "Détenteur",
    "Devon",
    "Disque ",
    "Dobok",
    "Dossard",
    "Douche",
    "Douche solaire",
    "Douille",
    "Draisienne",
    "Drapeau",
    "Driver",
    "Duvet",
    "Echarpe",
    "Echelle",
    "Echosondeur",
    "Eclairage de Plongée ",
    "Éclairage vélo",
    "Elastique ",
    "Elastique demi pointe",
    "Electro-Stimulation ",
    "Embout ",
    "Embout de guidon",
    "Emerillons",
    "Empenage",
    "Emporte pièces",
    "Enrênement",
    "Ensemble ",
    "Entretien vélo",
    "Entretoise",
    "Epaulière ",
    "Epée",
    "Éperon",
    "Éponge",
    "Équipement de secours",
    "Espalier ",
    "Etau à farter",
    "Etrier",
    "Étrille",
    "Etrivières",
    "Etui ",
    "Fanion",
    "Fart ",
    "Fer",
    "Fer à farter ",
    "Fil",
    "Fil et tresse",
    "Filet ",
    "Filet à foin",
    "Filet de pêche",
    "FIltre à eau",
    "Fixation ",
    "Flèche ",
    "Fleuret ",
    "Flotteur ",
    "Fond de jante",
    "Fourche ",
    "Fourche hydraulique ",
    "Fourches vélos",
    "Fourreau ",
    "Fourreau et étui",
    "Frein ",
    "Frein de ligne ",
    "Gant",
    "Garde boue",
    "Gaz propulseur ",
    "Gel",
    "Gélule",
    "Genouillères",
    "Gilet de plomb ",
    "Gilet de sauvetage ",
    "Gilet de sécurité ",
    "Gilet stabilisateur ",
    "Gilets de sauvetage ",
    "Glacière ",
    "Gogue",
    "Gomme",
    "Gonfleur",
    "Gourde ",
    "GPS",
    "Graisse (à cuir)",
    "Grip ",
    "Grips, extenseurs et câbles de résistance",
    "Groupe d'eau",
    "Guêtre ",
    "Guidage radio ",
    "Guidoline ",
    "Guidon ",
    "Guindeau",
    "Gyropode",
    "Hackamore",
    "Hakama ",
    "Haltère ",
    "Haltère ",
    "Hameçon",
    "Harnais ",
    "Harpon",
    "Head",
    "Home Trainer",
    "Housse ",
    "Housse vélo",
    "Huile pour cuir",
    "Hybride",
    "Impédancemètre ",
    "Imperméabilisant",
    "Imperméable",
    "Indicateur ",
    "Indicateur De Touche ",
    "Insecticide",
    "Jambière ",
    "Jeu de direction",
    "Jumelles ",
    "Kart",
    "Kayak ",
    "Kimono ",
    "Kit analyse de neige",
    "Kit de fixation",
    "Kit de lest",
    "Kit de pansage",
    "Kit de réparation",
    "Kit entretien",
    "Kneeboard",
    "Lacet ",
    "Laisse",
    "Lame ",
    "Lampe ",
    "Lampe frontale",
    "Lampe tactique",
    "Lampe torche",
    "Lance balle ",
    "Lanceur ",
    "Lanière d'éperon",
    "Leash",
    "Lest et plomb",
    "Lestes",
    "Leurres",
    "Leviers et manettes",
    "Licol ",
    "Ligne ",
    "Ligne mouillage",
    "Lime ",
    "Long board ",
    "Longe ",
    "Lot équipement - rollers",
    "Luge ",
    "Lunette de natation",
    "Lunette de protection ",
    "Lunette de visée ",
    "Lunettes",
    "Machine à corder ",
    "Machine à farter ",
    "Maillet",
    "Maillot de bain ",
    "Malette ",
    "Manchons",
    "Manomètre",
    "Marque-balle",
    "Marqueurs ",
    "Marteau",
    "Martingale",
    "Masque ",
    "Massue ",
    "Mât ",
    "Matelas ",
    "Mini chaps",
    "Modérateur de son",
    "Monoculaire",
    "Monocycle",
    "Monoski",
    "Montants de releveur",
    "Montre",
    "Montre GPS",
    "Mors",
    "Mors Baucher",
    "Mors de filet Chantilly",
    "Mors de filet Olive",
    "Mors de filet Verdun",
    "Mors de Pelham",
    "Moteur",
    "Mouches",
    "Moulinet ",
    "Mountainboard",
    "Mousqueton ",
    "Moustiquaire",
    "Moyeu",
    "Musclet",
    "Musculation",
    "Nattes tapis de sol",
    "Nettoyage",
    "Nunchaku ",
    "Nylon de pêche",
    "Ordinateur",
    "Ordinateur de Plongée ",
    "Oreiller",
    "Outils vélo",
    "Ouvreur automatique ",
    "Pack",
    "Pack d'accessoires",
    "Pack Longboard",
    "Pack Moutainboard",
    "Pack sécurité",
    "Pack Skateboard",
    "Pack Ski",
    "Pack Snowboard",
    "Paddle",
    "Pagaie ",
    "Palet ",
    "Palmes ",
    "Palonnier",
    "Panier ",
    "Panier à balles",
    "Panier de basket",
    "Pao",
    "Parachute ",
    "Parapente ",
    "Parapluie",
    "Pare battage",
    "Patch papillon",
    "Patin à roulettes ",
    "Patins à glace ",
    "Patte d'ours",
    "Peau",
    "Pédale ",
    "Pédalier",
    "Pegs",
    "Pelle",
    "Perle de pêche",
    "Peson",
    "Pignon",
    "Pince à cheveux",
    "Pince crocodile",
    "Pinceaux",
    "Pince-nez",
    "Piolet ",
    "Pistolet de starter",
    "Piton ",
    "Plafonnier",
    "Planche ",
    "Planches de Surf ",
    "Plaque",
    "Plaques de couche",
    "Plaquettes ",
    "Plastron ",
    "Plateau ",
    "Plateforme vibrante",
    "Platine",
    "Platine Roller ",
    "Plioir",
    "Plomb ",
    "Pneu ",
    "Poche",
    "Poche à eau",
    "Podomètre ",
    "Poids et kettlebells",
    "Poignée ",
    "Poignée d'ascension ",
    "Poing américain",
    "Pointe ",
    "Pointeur",
    "Poire de frappe",
    "Pommeau ",
    "Pompe",
    "Pompe à main ",
    "Pompe à pied ",
    "Popotes et couverts",
    "Portant ",
    "Porte bébé",
    "Porte bride",
    "Porte lampe",
    "Porte Seau",
    "Porte selle",
    "Porte-bagage ",
    "Porte-Bidons ",
    "Porte-Monnaie",
    "Porte-queue ",
    "Porte-Vélo ",
    "Poteau ",
    "Potence ",
    "Poudre",
    "Poulie ",
    "Poutre ",
    "Presse ",
    "Prince",
    "Prise d'escalade",
    "Procédé",
    "Procédé ",
    "Profondimètre",
    "Prolongateur ",
    "Propulseur",
    "Protection ",
    "Protection dorsale",
    "Protège avant-bras ",
    "Protège avant-bras ",
    "Protège boulets",
    "Protège hanche ",
    "Protège lame ",
    "Protège patin ",
    "Protège pieds",
    "Protège tendons",
    "Protège-cou ",
    "Protège-dents ",
    "Protège-jambe cheville ",
    "Protège-poignet ",
    "Protèges-pointes",
    "Protège-tibia ",
    "Punching-ball ",
    "Putter ",
    "Quad",
    "Queues de billard ",
    "Quille ",
    "Quillon ",
    "Racloir",
    "Raft ",
    "Ramasse-boules",
    "Rameur ",
    "Rampe",
    "Rangement ",
    "Râpe",
    "Raquette ",
    "Raquette de neige ",
    "Rasoir",
    "Réchaud",
    "Réflecteur",
    "Rênes",
    "Rênes allemandes",
    "Rênes supergrip",
    "Répulsif",
    "Réservoir",
    "Ressort",
    "Ressort de montée",
    "Retire bottes",
    "Rétroviseur ",
    "Revêtement",
    "Robot",
    "Roller ",
    "Roller ski ",
    "Roue ",
    "Roue libre et cassette",
    "Roulements à billes",
    "Ruban ",
    "Sabre ",
    "Sac",
    "Sac à eau",
    "Sac à magnésie",
    "Sac airbag",
    "Sac chariot",
    "Sac de combat",
    "Sac de couchage",
    "Sac de golf",
    "Sac et housse",
    "Sac harnais",
    "Sac Portable",
    "Sacoche bidon",
    "Sacoche cadre",
    "Sacoche porte-bagage",
    "Sacoche selle",
    "Sandow ",
    "Sangle ",
    "Savon à cuir",
    "Seau",
    "Selle ",
    "Selle de dressage",
    "Selle d'obstacle",
    "Selle mixte",
    "Selle Poney",
    "Selle randonnée",
    "Selle western",
    "Sellette ",
    "Semelle",
    "Semelle chauffante",
    "Séparation ",
    "Série",
    "Serviette de golf",
    "Set",
    "Set de chauffage",
    "Set de fartage ",
    "Sextant",
    "Shampoing pour chevaux",
    "Short de sécurité",
    "Short skate",
    "Siège ",
    "Sifflet ",
    "Skateboard ",
    "Ski ",
    "Slackline",
    "Snowblade (Miniski) ",
    "Snowboard ",
    "Soie mouche",
    "Soin",
    "Sonde",
    "Sondeur",
    "Sonnette",
    "Soufflette",
    "Sous Bandes",
    "Soutien, support et protection",
    "Spinner",
    "Stabilisateur",
    "Stepper ",
    "Steps et steppers",
    "Sticker",
    "Stop ski",
    "Strap",
    "Streetboard",
    "Support ",
    "Support de canne",
    "Surchaussures",
    "Surfaix de travail",
    "Surgrip",
    "Surpantalon",
    "Sursangle",
    "Surveste",
    "Survetement",
    "Table ",
    "Table d'arbitrage ",
    "Table de fartage ",
    "Tableau comande pompe de cale",
    "Tableau électrique",
    "Talonnette",
    "Tanto ",
    "Tapis ",
    "Tapis antidérapant ",
    "Tapis de course ",
    "Tapis de pliage ",
    "Tapis de selle ",
    "Tapis de sol ",
    "Tapis de Yoga",
    "Tapis d'entraînement",
    "Tatamis ",
    "Tee ",
    "Télémètre ",
    "Témoin de relais ",
    "Tendeur",
    "Tensiomètre",
    "Tente ",
    "Tente de camping",
    "Thermos",
    "Tige ",
    "Tir à l'arc ",
    "Tonfa ",
    "Tour de wakeboard",
    "Tracker",
    "Trampoline ",
    "Traversin ",
    "Trépied et siège",
    "Treuil",
    "Triangle ",
    "Tricoise",
    "Trompe ",
    "Trottinette ",
    "Trousse de réparation",
    "Trousse de secours ",
    "Truck ",
    "T-tool",
    "Tuba ",
    "Tube",
    "Variomètre ",
    "Vélo ",
    "Vélo d'appartement ",
    "Vélo de course ",
    "Vélo de ville ",
    "Vélo électrique",
    "Vélo pliant",
    "Vélo magnétique ",
    "Vélo Spinning",
    "Vélos Elliptiques ",
    "Vestes",
    "Vêtements et ceinture de sudation",
    "Vigil ",
    "Virole",
    "Vis ",
    "Viseur",
    "Visière ",
    "Visserie",
    "Voile ",
    "Volant ",
    "VTC ",
    "VTT ",
    "Waders",
    "Wakeboard",
    "Waveboard",
    "Wedge",
    "Wishbones"
]